###
POST http://localhost:4008/books
Content-Type: application/json

{
    "title": "Mulheres do Brasil: A história não contada ",
    "author": "Paulo Rezzutti"
}


###
GET http://localhost:4008/books

###
POST http://localhost:4008/search
Content-Type: application/json

{
    "author": "Ilan"
}


###
DELETE  http://localhost:4008/delete
Content-Type: application/json

{
    "_id": "617a66fd004933070e74a950"
}


###
PATCH http://localhost:4008/edit
Content-Type: application/json

{
    "_id": "617a66fd004933070e74a94e",
    "author": "Ilan Pappéeeee"
}